### ISSUE TITLE
adsf-live does not work with rack 3

### ISSUE THREAD

**Issue by Fjan** [denisdefreyne/adsf#29]
Adsf version 1.4.7 started using lower case headers to support rack 3, however the rack-livereload gem that adsf-live depends on has not yet been updated and expects upper case headers. I realise this is something that needs to be updated in the rack-livereload gem, but that project seems dormant. 

Until that gem gets updated, I created this monkey patch that seems to work:
``` ruby
module Rack
  class LiveReload

    class ProcessingSkipAnalyzer
      def html?;@headers['content-type'] =~ %r{text/html}; end
    end

    def call(env)
      result = dup._call(env)
      if (headers=result[1]).is_a?(Hash) && headers['Content-Length']
        headers['content-length']=headers.delete('Content-Length')
        headers.transform_keys!{_1.downcase}
      end
      result
    end

  end
end
```

It's a bit tricky to get the patch to load at the right time when used with nanoc, I ended up creating a custom nanoc command.

**Comment by denisdefreyne** [comment]
Thanks for reporting!

Here is a bunch more background written up by @pcantrell: https://github.com/nanoc/features/issues/66 -- and a PR to the most relevant `rack-livereload` repository: https://github.com/jaredmdobson/rack-livereload/pull/13

The `rack-livereload` repository doesn’t seem to be publishing new gems, which is a problem (because Rubygems doesn’t support having dependencies on Git repositories, just on published gems). There’s an issue open asking for a new release (https://github.com/jaredmdobson/rack-livereload/issues/10) but so far no movement there.

Not having livereload in Nanoc sucks (I need it) so I might fork `rack-livereload` and publish my own gem of it, likely this weekend -- I suspect that’ll happen when I start making changes to my own site and realise it’s not working as intended!

CC @pcantrell

**Comment by Fjan** [comment]
The recently updated rack-livereload gem [fixed](https://github.com/jaredmdobson/rack-livereload/pull/13) this 🎉
